name: imgur
description: >-
  An Imgur api client for Dart.
version: 1.0.0
homepage: https://github.com/shellbear/imgur.dart
repository: https://github.com/shellbear/imgur.dart
author: shellbear <shellbear@protonmail.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  http: ^0.12.0+2
  json_annotation: ^3.0.0

dev_dependencies:
  build_runner: ^1.7.1
  json_serializable: ^3.2.3
  pedantic: ^1.8.0
  test: ^1.6.0
